/**
 * Sprite storage and blitting for the hero runner.
 *
 * A sprite is a `Bitmap`: an array of equal-length strings, one string per
 * pixel row. Each character is a palette key; `.` — or any character that is
 * not a key in the palette — is transparent. Bitmaps are authored at the
 * simulation's own scale, so a player bitmap is exactly
 * `PLAYER_SPRITE_WIDTH` x `PLAYER_SPRITE_HEIGHT` and blits 1:1 onto the
 * player's world box with no anchoring maths.
 *
 * The art comes from `src/assets/runner/skateboard-sheet.jpg`, a generated
 * sprite sheet. `scripts/build-sprites.ts` cuts the frames out of it, removes
 * the sheet's background, downsamples each frame to the 16x22 player box, and
 * splices the palette and `PLAYER_SPRITES` literals below between the
 * `generated:start` / `generated:end` markers. **Do not edit that block by
 * hand** — edit the sheet or the generator and re-run it. Everything outside
 * the markers (this header, the size constants, the import-time assertion and
 * `drawBitmap`) is hand-maintained.
 *
 * `PLAYER_PALETTE` is a five-step stone ramp drawn from colours the site
 * already uses, so the finished sprite reads as part of the monochrome
 * `game-night-light` hero rather than as a new colour system. The sheet is a
 * single warm greyscale figure, so the keys are ramp positions rather than
 * body parts: `o` darkest through `l` lightest.
 *
 * This module is data plus one blit helper. It has no DOM dependency: the only
 * reference to `CanvasRenderingContext2D` is type-only, so the file can be
 * imported by Node (see `scripts/verify-sprites.ts`) without a canvas.
 */

import type { Pose } from "./runner";

export type Bitmap = readonly string[];

/** Every player bitmap is authored at the simulation's player box size. */
export const PLAYER_SPRITE_WIDTH = 16;
export const PLAYER_SPRITE_HEIGHT = 22;

// --- generated:start ---
// Generated by scripts/build-sprites.ts from
// src/assets/runner/skateboard-sheet.jpg. Do not edit by hand; edit the
// sheet or the generator and re-run it.

export const PLAYER_PALETTE: Readonly<Record<string, string>> = {
	o: "#1c1917",
	d: "#44403c",
	m: "#78716c",
	s: "#a8a29e",
	l: "#d6d3d1",
};

export const PLAYER_SPRITES: Readonly<Record<Pose, readonly Bitmap[]>> = {
	idle: [
		[
			".......o.dooo...",
			"......dddddddoo.",
			".....odddddddd..",
			".....ooododdddo.",
			".....odoodddddo.",
			".....oddommmmo..",
			".....oododmddd..",
			".....oommmmddd..",
			"......oodmmmd...",
			".......oodmmd...",
			"...dd.dddddoo...",
			"..odddmmdoddd...",
			"..oooodomdodd...",
			"..odddmdmmdooo..",
			".dddddsooododo..",
			"..odddsoddddd...",
			"..odddsdmddmo...",
			"..oddddddodmo...",
			"..odddoddoddo...",
			"..dddodmooodm...",
			"..oddomsd.dddo..",
			"...ooooo........",
		],
		[
			"....o.doo.......",
			"...dddddddo.....",
			"..odddddddd.....",
			"..ooododdddo....",
			"..odoodddddo....",
			"..ddodmmmmo.....",
			"..odoommddd.....",
			"..odmdmmddd.....",
			"...oodmmmd......",
			"....oodmd.......",
			"...dddddo.......",
			"..oddddoo.......",
			"..omoddddd..o...",
			"..ddoodmoo.odo..",
			"..dmoodoododdo..",
			"..mdodddoodddo..",
			"...odmdmoodddd..",
			"...omdoddddo....",
			"...odoodddo.....",
			"...dmooddo......",
			"...ddodddd......",
			"......ooo.......",
		],
	],
	push: [
		[
			"................",
			"................",
			"................",
			"................",
			"........ooooo...",
			".......odddddo..",
			".......ddddddo..",
			"......oddddddo..",
			".......oodmddo..",
			".......odmddmd..",
			".......dodmmd...",
			".....odddddd....",
			".....ddddddd....",
			"....dmomdddd....",
			"....mdodddodd...",
			"....mddmodmdd...",
			".....oddddddo...",
			"do..ddodsddd..od",
			"dddodmdooddmdodm",
			"ddmmdddmmmdddmd.",
			"..ododdddddddo..",
			"...d........d...",
		],
		[
			"................",
			"................",
			"................",
			"................",
			"................",
			"........ooooo...",
			".......odddddo..",
			".......ddddddo..",
			"......oddddddo..",
			".......oodmddo..",
			".......odmddmd..",
			".......dodmmd...",
			".....odddddd....",
			".....ddddddd....",
			"....dmomdddd....",
			"....mdodddodd...",
			"....mddmodmdd...",
			"do..ddodsddd..od",
			"dddodmdooddmdodm",
			"ddmmdddmmmdddmd.",
			"..ododdddddddo..",
			"...d........d...",
		],
	],
	ride: [
		[
			"................",
			"................",
			"................",
			".......oodoo....",
			".....oodddddo...",
			".....oddddddd...",
			".....oddddddoo..",
			"......oodmddo...",
			"......ddmdomd...",
			".....dodmmmd....",
			".mdddmdddddo.o..",
			".mdoooddoddmdmm.",
			".....omdddooood.",
			".....odddodo....",
			".....dddommmo...",
			".....dmdddddo...",
			"....oddmlsoo....",
			"ddodmoodmddmoodd",
			"dddomdooooddoddd",
			"dddddddddddddddd",
			".ddddddddddddd..",
			"...dd......dd...",
		],
		[
			"................",
			"................",
			"........oooo....",
			"......odddddoo..",
			"......oddddddo..",
			"......oddddddo..",
			"......oooddddo..",
			".......ddmddm...",
			".......oddmm....",
			"......dodddd....",
			"....oddddddd....",
			"...oddoddodd....",
			"...mdddmmdodo...",
			"...md.ooddodm...",
			".....oddddddm...",
			".....dmdddmd....",
			"....oddmlddo....",
			"do.dmodssddd..od",
			"ddodmddooddmdodd",
			"ddmddmmmmmdddmdd",
			"..odoooddodddo..",
			"...d........d...",
		],
	],
	jump: [
		[
			".......ooooo....",
			".....oddddddoo..",
			".....oddddddo...",
			".....oddddoddo..",
			".....ododdmdo...",
			".....ooomdomd...",
			"......ddmddmd...",
			"...oddoodmmo....",
			".odmddddodddoo..",
			"dmdooddooddddmm.",
			".md.odmdddo.odd.",
			"....oooddodd....",
			"...ddmddddmm....",
			"...omddddodd....",
			"....doolsodm..od",
			"....dddlsdmddddd",
			"....mmslsmooddd.",
			"....odmddddddo..",
			"doodddddddd.oo..",
			"ddddddd.........",
			".dddo...........",
			"...dd...........",
		],
	],
	dead: [
		[
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"...ddddddd......",
			"..ddddddddd.....",
			"..ddsssssdd.....",
			"..doooooood.....",
			"..dollollod.....",
			"..dsssssssd.....",
			"..ddddddddd.....",
			"...ssssss.......",
			"..mmmmmmmmmm.dd.",
			"..mmmmmmmmmm.dd.",
			".ddddddddddd.ddl",
			"ddd......dddddd.",
			"ooo.......oo.dd.",
		],
	],
};
// --- generated:end ---

/**
 * Structural guard, run once at import. A wrong-sized bitmap would silently
 * mis-anchor the player (the box is fixed at 16x22 and the blit assumes 1:1),
 * so fail loudly instead of drawing a sheared character.
 */
function assertBitmapSizes(): void {
	for (const [pose, frames] of Object.entries(PLAYER_SPRITES)) {
		frames.forEach((bitmap, index) => {
			if (bitmap.length !== PLAYER_SPRITE_HEIGHT) {
				throw new Error(
					`runner-sprites: ${pose}[${index}] has ${bitmap.length} rows, expected ${PLAYER_SPRITE_HEIGHT}`,
				);
			}
			bitmap.forEach((row, y) => {
				if (row.length !== PLAYER_SPRITE_WIDTH) {
					throw new Error(
						`runner-sprites: ${pose}[${index}] row ${y} has ${row.length} columns, expected ${PLAYER_SPRITE_WIDTH}`,
					);
				}
			});
		});
	}
}
assertBitmapSizes();

/**
 * Blit a bitmap to the canvas as batched rects.
 *
 * `x`/`y` are the bitmap's top-left in world units and `px` is CSS px per world
 * unit, so the caller passes `s.player.x`, `s.player.y` and `pixelScale`
 * unchanged. Cells are grouped by colour first and each colour is drawn with a
 * single `beginPath()` / `rect()`-per-cell / `fill()`, matching the ground
 * texture's idiom: one rasterisation per colour instead of one per pixel.
 * Transparent cells (any key missing from `palette`) are skipped.
 */
export function drawBitmap(
	ctx: CanvasRenderingContext2D,
	bitmap: Bitmap,
	palette: Record<string, string>,
	x: number,
	y: number,
	px: number,
): void {
	const groups = new Map<string, { x: number; y: number }[]>();
	for (let row = 0; row < bitmap.length; row++) {
		const line = bitmap[row];
		for (let col = 0; col < line.length; col++) {
			const colour = palette[line[col]];
			if (colour === undefined) continue;
			let cells = groups.get(colour);
			if (cells === undefined) {
				cells = [];
				groups.set(colour, cells);
			}
			cells.push({ x: col, y: row });
		}
	}
	for (const [colour, cells] of groups) {
		ctx.fillStyle = colour;
		ctx.beginPath();
		for (const cell of cells) {
			ctx.rect((x + cell.x) * px, (y + cell.y) * px, px, px);
		}
		ctx.fill();
	}
}
