/**
 * Sprite storage and blitting for the hero runner.
 *
 * The player art is a set of transparent PNG frames, one per pose frame, under
 * `public/runner/player/`. They are kept **at the sheet's own resolution** — the
 * art is not downsampled — and scaled into the player's 16x22 world box at blit
 * time by `drawPlayerFrame`. `PLAYER_FRAMES` maps each pose to its frame URLs in
 * play order; the simulation indexes it by `player.frame % frames.length`, so a
 * one-frame pose (jump, dead) holds frame 0.
 *
 * The art comes from `src/assets/runner/skateboard-sheet.jpg`, a generated
 * sprite sheet. `scripts/build-sprites.ts` cuts the frames out of it, removes
 * the sheet's background, writes the PNGs, and splices the `PLAYER_FRAMES`
 * manifest below between the `generated:start` / `generated:end` markers. **Do
 * not edit that block by hand** — edit the sheet or the generator and re-run it.
 * Everything outside the markers (this header, the size constants and
 * `drawPlayerFrame`) is hand-maintained.
 *
 * This module is data plus one blit helper. It has no DOM dependency: the only
 * references to `CanvasRenderingContext2D` and `CanvasImageSource` are
 * type-only, so the file can be imported by Node (see `scripts/verify-sprites.ts`)
 * without a canvas.
 */

import type { Pose } from "./runner";

/** The simulation's player box, in world units. Sprites are fitted into it. */
export const PLAYER_SPRITE_WIDTH = 16;
export const PLAYER_SPRITE_HEIGHT = 22;

/** Anything `drawImage` accepts that reports its intrinsic pixel size. */
export type SpriteImage = CanvasImageSource & {
	readonly width: number;
	readonly height: number;
};

// --- generated:start ---
// Generated by scripts/build-sprites.ts from
// src/assets/runner/skateboard-sheet.jpg. Do not edit by hand; edit the
// sheet or the generator and re-run it.

export const PLAYER_FRAMES: Readonly<Record<Pose, readonly string[]>> = {
	idle: ["/runner/player/idle-0.png", "/runner/player/idle-1.png"],
	push: ["/runner/player/push-0.png", "/runner/player/push-1.png"],
	ride: ["/runner/player/ride-0.png", "/runner/player/ride-1.png"],
	jump: ["/runner/player/jump-0.png"],
	dead: ["/runner/player/dead-0.png"],
};
// --- generated:end ---

/**
 * Blit one player frame into the 16x22 world box.
 *
 * The image is fitted with `contain` and anchored to the bottom-centre of the
 * box: the sprite's feet (or board) sit on the box's bottom edge, and a
 * narrower pose is centred horizontally. `x`/`y` are the box's top-left in world
 * units and `px` is CSS px per world unit, so the caller passes `s.player.x`,
 * `s.player.y` and `pixelScale` unchanged. Because the source frames carry far
 * more detail than the 16x22 box, the draw is a high-quality downscale; the
 * canvas smoothing settings are the component's to set.
 */
export function drawPlayerFrame(
	ctx: CanvasRenderingContext2D,
	image: SpriteImage,
	x: number,
	y: number,
	px: number,
): void {
	const iw = image.width;
	const ih = image.height;
	if (iw <= 0 || ih <= 0) return;
	const scale = Math.min(PLAYER_SPRITE_WIDTH / iw, PLAYER_SPRITE_HEIGHT / ih);
	const w = iw * scale;
	const h = ih * scale;
	const dx = x + (PLAYER_SPRITE_WIDTH - w) / 2;
	const dy = y + (PLAYER_SPRITE_HEIGHT - h);
	ctx.drawImage(image, dx * px, dy * px, w * px, h * px);
}
